### ISSUE TITLE
missing /img_dev directory in rootfs

### ISSUE THREAD

**Issue by sehari24jam** [KaOSx/live#1]
In hook/kdeosiso_loop_mnt, will try to mount loop ISO-file into /img_dev, which is not exist.

This will fail the hook, and drop interactive shell.

**Comment by demmm** [comment]
And why wouldn't it exists? What ISO are you referring to?

**Comment by sehari24jam** [comment]
The latest ISO: KaOS-2015.02-x86_64.iso.

I were doing testing, to boot LiveISO from file in my filesystem, using grub2.
The process was stop, due to missing /img_dev.
I have to trick the hook, so it drop into interactive shell and fix the missing folder, then exit from interactive shell. At the end, it will successfully boot the LiveISO.

This is my grub.cfg to boot the LiveISO:

menuentry "KaOS: KaOS-2015.02-x86_64" {
	insmod part_gpt
	insmod ext2
	set root='(hd0,gpt2)'
	search --no-floppy --fs-uuid --set=root 9c0054e2-76c4-4dcd-810b-6ef7629565da
	set isofile=/boot/images/KaOS-2015.02-x86_64.iso
	loopback loop $isofile
	linux  (loop)/kdeos/boot/x86_64/kdeosiso img_loop=$isofile img_dev=/dev/kaos kdeosisolabel=KAOS_20150220 showopts nonfree=yes xdriver=no i915.modeset=1 nouveau.modeset=1 radeon.modeset=1
	initrd (loop)/kdeos/boot/x86_64/kdeosiso.img
}


The dev=/dev/kaos was the trick, so interactive shell show up and let me recreate /img_dev:

mkdir /img_dev
ln -svn /dev/sda2 /dev/kaos ### create symlink to partition where the ISO is kept.
exit ### continue boot, successfully start livecd

**Comment by sehari24jam** [comment]
The line in question: live/live-iso/hooks/kdeosiso_loop_mnt #23

  if mount -r -t "${FSTYPE}" ${img_dev} /img_dev > /dev/null 2>&1; then

**Comment by demmm** [comment]
Not clear at all what you're issue is, but this is certainly the wrong place to report an issue with an ISO.
This repo is no longer in use, plus there is no indication is you checked any for the correctness  of your live-media, closing.
